pubnative/pubnative-hybid-ios-sdk

PubnativeLite/PubnativeLite/Ad Model/PNLiteAd.h
PubnativeLite/PubnativeLite/Ad Model/PNLiteAd.m
PubnativeLite/PubnativeLiteDemo/DFP/PNLiteDemoDFPBannerViewController.m
PubnativeLite/PubnativeLiteDemo/DFP/PNLiteDemoDFPInterstitialViewController.m
PubnativeLite/PubnativeLiteDemo/DFP/PNLiteDemoDFPMRectViewController.m
PubnativeLite/PubnativeLiteDemo/MoPub/PNLiteDemoMoPubBannerViewController.m
PubnativeLite/PubnativeLiteDemo/MoPub/PNLiteDemoMoPubInterstitialViewController.m
PubnativeLite/PubnativeLiteDemo/MoPub/PNLiteDemoMoPubMRectViewController.m
PubnativeLite/PubnativeLiteDemo/Storyboards/Banner.storyboard
PubnativeLite/PubnativeLiteDemo/Storyboards/Interstitial.storyboard
PubnativeLite/PubnativeLiteDemo/Storyboards/MRect.storyboard

[MI-274] Get ImpressionID on Ads

Retrieving ImpressionID property functionality added.

---

PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.m
PubnativeLite/PubnativeLite/Consent/PNLiteUserConsentResponseModel.m

- Caching Device ID to detect whether consent was given or not
- Fixes in CMP Logic

[MI-292] Caching Device ID to detect whether consent was given or not

---

PubnativeLite/AdSDK Demo/AdSdkDemoSettings.h
PubnativeLite/AdSDK Demo/AppDelegate.m
PubnativeLite/AdSDK Demo/SceneDelegate.m
PubnativeLite/PubnativeLite/Ad Model/HyBidAd.m
PubnativeLite/PubnativeLite/Ad Model/HyBidAdModel.h
PubnativeLite/PubnativeLite/Ad Model/HyBidAdModel.m
PubnativeLite/PubnativeLite/Ad Model/VrvResponseModel.h
PubnativeLite/PubnativeLite/Ad Model/VrvResponseModel.m
PubnativeLite/PubnativeLite/Ad Request/HyBidAdRequest.m
PubnativeLite/PubnativeLite/Ad Request/VrvAdFactory.h
PubnativeLite/PubnativeLite/Ad Request/VrvAdFactory.m
PubnativeLite/PubnativeLite/Ad Request/VrvAdRequestModel.h
PubnativeLite/PubnativeLite/Ad Request/VrvAdRequestModel.m
PubnativeLite/PubnativeLite/HyBidAdView.m

During my investigation i found some stuff that can be enhanced or fixed.

Some fixes and enhancements for IQV SDK

---

PubnativeLite/PubnativeLite/HyBid.h
PubnativeLite/PubnativeLite/HyBid.m
PubnativeLite/PubnativeLiteDemo/PNLite/PNLiteDemoPNLiteSettingsViewController.m

OMI-406: adding reconfigure function as an alias to iniWithAppToken
- Use reconfigure in the demo app when settings change.

adding reconfigure function

---

HyBid.podspec
PubnativeLite/PubnativeLite/HyBidConstants.h
PubnativeLite/PubnativeLite/Info.plist
PubnativeLite/PubnativeLite/Utils/Country/PNLiteCountryUtils.m

- Update CountryUtils with country codes.

UserDataManager consent updates

---

PubnativeLite/PubnativeLite/Ad Model/HyBidAd.m

width & height was not retrieved when MRAIDView is created.

[OMI-414] Fixed the banner rendering issue.

---

HyBidDemo/HyBidDemoSwift/AppDelegate.swift
PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/Ad Request/VWAdFactory.m
PubnativeLite/PubnativeLite/Consent/VWAdLibrary.h
PubnativeLite/PubnativeLite/Consent/VWAdLibrary.m
PubnativeLite/PubnativeLite/HyBid.h
PubnativeLite/PubnativeLite/HyBidStatic.h

- add VWAdLibrary including ccpa functions.
- add usprivacy string to verve ad request.
- Set us privacy string in swift demo app.

OMI-421: add CCPA Support.

---

PubnativeLite/PubnativeLite/Network/PNLiteHttpRequest.m

- Remove the user agent from the url session
- Add web view user agent to the NSUrlRequest object in the HTTP client

[OMI-454] Add WebView User agent to HTTP requests

---

PubnativeLite/PubnativeLite/Ad Request/PNLiteAdFactory.m
PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.h
PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.m

Both code and GitHub Wiki integration is added. 
For GitHub Wiki please check: https://github.com/pubnative/pubnative-hybid-ios-sdk/wiki/CCPA-Compliance

CCPA support/compliance

---

PubnativeLite/PubnativeLite/Ad Request/HyBidRequestParameter.h
PubnativeLite/PubnativeLite/Ad Request/HyBidRequestParameter.m
PubnativeLite/PubnativeLite/Ad Request/PNLiteAdFactory.m
PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.h
PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.m

CCPA Compliance & as an AdRequestParam is added to minusMoPub branch

---

PubnativeLite/PubnativeLite/HyBid.h
PubnativeLite/PubnativeLite/HyBid.m
PubnativeLite/PubnativeLite/Location/PNLiteLocationManager.h
PubnativeLite/PubnativeLite/Location/PNLiteLocationManager.m
PubnativeLite/PubnativeLiteDemo/AppDelegate.m
PubnativeLite/PubnativeLiteDemo/Info.plist

- Add `locationUpdatesEnabled` flag to `HyBid` to enable/disable location updates.
- Add a quick test for location in `HyBidDemo`

add flag to location update + test in HyBid demo.

---

PubnativeLite/PubnativeLite/Ad Request/HyBidRequestParameter.h
PubnativeLite/PubnativeLite/Ad Request/HyBidRequestParameter.m
PubnativeLite/PubnativeLite/Ad Request/PNLiteAdFactory.m

To the branch that has MoPub SDK 5.13.0

Adding location params to AdRequest

---

PubnativeLite/PubnativeLite/Tracking/HyBidVisibilityTracker.m

- checkVisiblity should run on main thread.

Fix runtime UI issues with native ads.

---

PubnativeLite/PubnativeLite/VAST/PNLiteVASTPlayerViewController.m

- Add NSNotifcations to trigger when app is in background, then track pause event. 
- When app is active again, track resume event.

omsdk:  fix videoevents

---

PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/Ad Request/HyBidAdRequest.m
PubnativeLite/PubnativeLite/Ad Request/VWAdFactory.m
PubnativeLite/PubnativeLite/Utils/HyBidLocationEncoding.h
PubnativeLite/PubnativeLite/Utils/HyBidLocationEncoding.m
PubnativeLite/PubnativeLite/Utils/HyBidXMLDictionary.h
PubnativeLite/PubnativeLite/Utils/HyBidXMLDictionary.m

- Prefix "HyBid" to XMLDictionary and LocationEncoding classes

[OMI-500] Prefix some classes with HyBid

---

.circleci/config.yml
HyBid.podspec
PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/HyBidConstants.h
PubnativeLite/PubnativeLite/Info.plist
PubnativeLite/PubnativeLite/Interstitial/PNLiteMRAIDInterstitialPresenter.m
PubnativeLite/PubnativeLite/MRAID/HyBidMRAIDView.m
PubnativeLite/PubnativeLite/MRAID/PNLiteMRAIDUtil.m
PubnativeLite/PubnativeLite/MRAID/hybidmraidscaling.js
PubnativeLite/PubnativeLite/MRAID/hybidscaling.js
PubnativeLite/PubnativeLiteDemo/Adapters/MoPubAdapter/HyBidAdapterConfiguration.m
PubnativeLite/PubnativeLiteDemo/Info.plist

- Move MRAID injection to MRAIDUtil class
- Add scaling script to SDK

Scale HTML interstitials with hardcoded size 320x480

---

HyBidDemo/HyBidDemoObjc/Controllers/BannerViewController.m
HyBidDemo/HyBidDemoObjc/Controllers/MRectViewController.m
HyBidDemo/HyBidDemoSwift/Controllers/BannerViewController.swift
HyBidDemo/HyBidDemoSwift/Controllers/MRectViewController.swift

- Set auto show on load for banner placements on both demo apps

[OMI-525] Fix duplicated impressions on Objc and Swift demo apps

---

HyBid.podspec
PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/Consent/HyBidUserDataManager.m
PubnativeLite/PubnativeLite/HyBidConstants.h
PubnativeLite/PubnativeLite/Info.plist
PubnativeLite/PubnativeLiteDemo/Adapters/MoPubAdapter/HyBidAdapterConfiguration.m

- Add TCF 2.0 consent string key to UserDataManager

[OMI-526] Add TCF 2.0 consent string key to user data manager

---

PubnativeLite/PubnativeLite/Interstitial/HyBidInterstitialAd.m

There is duplicated code when parsing signal response. That approach will be refactored.

MaxAds Mediation support is added to HyBid SDK after merging

---

PubnativeLite/PubnativeLite/Ad Model/HyBidAd.m
PubnativeLite/PubnativeLite/Ad Request/PNLiteAdFactory.m

- Fix SKAdNetwork version on ad request
- Add min version of 11.3 to add SKAdNetwork params
- Remove test data from HyBidAd model

Fix SKAdNetwork version check

---

PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventBanner.h
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventBanner.m
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventInterstitial.h
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventInterstitial.m
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventNative.h
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AMCustomEventNative.m
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AppMonet+MoPub.h
PubnativeLite/PubnativeLiteDemo/Adapters/AppMonet Adapters/MoPub Adapters/AppMonet+MoPub.m
PubnativeLite/PubnativeLiteDemo/Adapters/MoPubAdapter/Mediation/HyBidMoPubMediationBannerCustomEvent.m
PubnativeLite/PubnativeLiteDemo/Adapters/MoPubAdapter/Mediation/HyBidMoPubMediationLeaderboardCustomEvent.m
PubnativeLite/PubnativeLiteDemo/Adapters/MoPubAdapter/Mediation/HyBidMoPubMediationMRectCustomEvent.m

Base class for native is also created here. But functionality is not finished. It'll be done in a separate branch as it is a separate ticket (OMI-602)

[OMI-601] HyBid SDK extension for MoPub Mediation (minus Native)

---

PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/Ad Request/HyBidAdRequest.m
PubnativeLite/PubnativeLite/Auction/AdSource.h
PubnativeLite/PubnativeLite/Auction/AdSource.m
PubnativeLite/PubnativeLite/Auction/AdSourceConfig.h
PubnativeLite/PubnativeLite/Auction/AdSourceConfig.m
PubnativeLite/PubnativeLite/Auction/AdSourceConfigParameter.h
PubnativeLite/PubnativeLite/Auction/AdSourceConfigParameter.m
PubnativeLite/PubnativeLite/Auction/Auction.m
PubnativeLite/PubnativeLite/Auction/HyBidAdSource.m
PubnativeLite/PubnativeLite/Auction/VastTagAdSource.m
PubnativeLite/PubnativeLite/HyBid.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigEndpoints.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigEndpoints.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigManager.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigManager.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigMeasurement.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigMeasurement.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigModel.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigModel.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigParameter.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigParameter.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigPlacement.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigPlacement.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigPlacementInfo.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigPlacementInfo.m
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigRequest.h
PubnativeLite/PubnativeLite/Remote Config/HyBidRemoteConfigRequest.m

- Port remote config classes from Voyager project.
- Map/cleanup remote config data following [ this sample file:](https://hybid-remote-config.herokuapp.com/)
- Fix auctions classes with the new config.

port remote config from voyager + map auction for remote config data.

---

.circleci/config.yml
Analytics/Analytics.xcodeproj/project.pbxproj
Analytics/Analytics/Analytics.h
Analytics/Analytics/Info.plist
Analytics/Analytics/ReportingEvent.swift
Analytics/Analytics/ReportingManager.swift
Analytics/Analytics/ReportingProperties.swift
HyBid.xcworkspace/contents.xcworkspacedata
PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLite/Core/Ad Model/HyBidAdSize.m
PubnativeLite/PubnativeLite/Core/HyBid.h
PubnativeLite/PubnativeLite/Core/HyBid.m
PubnativeLite/PubnativeLiteDemo/AppDelegate.h
PubnativeLite/PubnativeLiteDemo/AppDelegate.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteBannerViewController.m
PubnativeLite/Scripts/generate.sh
PubnativeLite/Scripts/generate_banner_only.sh
PubnativeLite/Scripts/generate_fullscreen_only.sh
PubnativeLite/Scripts/generate_native_only.sh
PubnativeLite/Scripts/generate_rewardedvideo_only.sh

Analytics Architecture: 
- Create a swift project (Analytics.framework) as a dependency to HyBid including broadcasting/listening to analytics events.
- Create a sample event in banner request in HyBidDemo. The listener is set on AppDelegate.

Development anayltics architecture

---

Analytics/Analytics/HyBidReportingEvent.swift
Analytics/Analytics/HyBidReportingProperties.swift
Analytics/Analytics/ReportingProperties.swift
PubnativeLite/HyBid.xcodeproj/project.pbxproj
PubnativeLite/PubnativeLiteDemo/Analytics/AnalyticsEventTableViewCell.h
PubnativeLite/PubnativeLiteDemo/Analytics/AnalyticsEventTableViewCell.m
PubnativeLite/PubnativeLiteDemo/Analytics/AnalyticsViewController.h
PubnativeLite/PubnativeLiteDemo/Analytics/AnalyticsViewController.m
PubnativeLite/PubnativeLiteDemo/PNLiteDemoBaseViewController.h
PubnativeLite/PubnativeLiteDemo/PNLiteDemoBaseViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteBannerViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteInterstitialViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteNativeAdViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteRewardedViewController.m
PubnativeLite/PubnativeLiteDemo/Storyboards/Analytics.storyboard
PubnativeLite/PubnativeLiteDemo/Storyboards/Settings.storyboard

Analytics Debug Screen:
- Add Analytics debug screen to HyBid Demo settings showing all broadcasted events. 
- Add ad requests events to banner, interstitial, native, and rewarded video.

Development analytics demo

---

Analytics/Analytics.xcodeproj/project.pbxproj
Analytics/Analytics/HyBidReporting.swift
Analytics/Analytics/HyBidReportingEvent.swift
Analytics/Analytics/HyBidReportingProperties.swift
HyBid.xcworkspace/contents.xcworkspacedata
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityAdSession.m
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityManager.h
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityManager.m
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityNativeAdSession.m
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityNativeVideoAdSession.m
PubnativeLite/PubnativeLite/Core/Viewability/HyBidViewabilityWebAdSession.m
PubnativeLite/PubnativeLiteDemo/Analytics/AnalyticsViewController.m
PubnativeLite/PubnativeLiteDemo/PNLiteDemoBaseViewController.h
PubnativeLite/PubnativeLiteDemo/PNLiteDemoBaseViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteBannerViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteInterstitialViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteNativeAdViewController.m
PubnativeLite/PubnativeLiteDemo/Standalone/PNLiteDemoPNLiteRewardedViewController.m
PubnativeLite/PubnativeLiteDemo/Storyboards/Analytics.storyboard

- reporting omsdk events via Analytics framework. 
@eros902002 @abanoubdev: 
I changed the properties keys so have a look at `HyBidReporting.swift` to make it consistent between the 2 platforms.

Development omsdk analytics
